# Generated by Django 4.2.5 on 2023-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coords',
            new_name='Coord',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level_autumn',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level_spring',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level_summer',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level_winter',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
